; Local extensions to tomte's canonical tox.ini. Consumed by `tomte tox`.

[tomte-extensions]
extra_deps =
    protobuf<6,>=5
    aiohttp<4.0.0,>=3.8.5
    py-ecc<10,>=8
    websocket_client<1,>=0.32.0
    prometheus_client>=0.23.1,<0.24
    pebble>=5.1,<6
    pyyaml<7.0.0,>=6.0.0
    werkzeug==3.1.6
    attrs==25.4.0
    pytest-asyncio>=1.3
    ecdsa>=0.15
    certifi
    multidict
    typing_extensions<=4.15.0,>=3.10.0.2
    eth_typing

[pytest]
tomte_defaults = true
addopts = -p no:pytest_anchorpy
asyncio_mode = strict

[mypy]
warn_unused_ignores = False
warn_redundant_casts = False
disable_error_code = redundant-cast,unused-ignore

[mypy-packages.valory.skills.agent_db_abci.tests.*]
ignore_errors = True

[mypy-packages.valory.connections.twikit.tests.*]
ignore_errors = True

[mypy-packages.valory.connections.tweepy.tests.*]
ignore_errors = True

[mypy-packages.valory.connections.abci.*]
ignore_errors = True

[mypy-packages.valory.connections.http_client.*]
ignore_errors = True

[mypy-packages.valory.connections.http_server.*]
ignore_errors = True

[mypy-packages.valory.connections.ipfs.*]
ignore_errors = True

[mypy-packages.valory.connections.ledger.*]
ignore_errors = True

[mypy-packages.valory.connections.p2p_libp2p_client.*]
ignore_errors = True

[mypy-packages.valory.contracts.gnosis_safe.*]
ignore_errors = True

[mypy-packages.valory.contracts.gnosis_safe_proxy_factory.*]
ignore_errors = True

[mypy-packages.valory.contracts.multisend.*]
ignore_errors = True

[mypy-packages.valory.contracts.service_registry.*]
ignore_errors = True

[mypy-packages.valory.contracts.erc20.*]
ignore_errors = True

[mypy-packages.valory.protocols.*]
ignore_errors = True

[mypy-packages.valory.skills.abstract_abci.*]
ignore_errors = True

[mypy-packages.valory.skills.abstract_round_abci.*]
ignore_errors = True

[mypy-packages.valory.skills.registration_abci.*]
ignore_errors = True

[mypy-packages.valory.skills.reset_pause_abci.*]
ignore_errors = True

[mypy-packages.valory.skills.termination_abci.*]
ignore_errors = True

[mypy-packages.valory.skills.transaction_settlement_abci.*]
ignore_errors = True

[mypy-twikit.*]
ignore_missing_imports = True

[mypy-tweepy.*]
ignore_missing_imports = True

[mypy-twitter_text_parser.*]
ignore_missing_imports = True

[mypy-textblob.*]
ignore_missing_imports = True

[mypy-peewee.*]
ignore_missing_imports = True

[mypy-js2py.*]
ignore_missing_imports = True

[mypy-rich.*]
ignore_missing_imports = True

[mypy-pydantic]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-aiohttp]
ignore_missing_imports = True

[mypy-aiohttp.*]
ignore_missing_imports = True

[mypy-eth_account]
ignore_missing_imports = True

[mypy-eth_account.*]
ignore_missing_imports = True


[Authorized Packages]
open-autonomy: ==0.21.22
anchorpy: 0.20.2
based58: 0.1.1
jsonalias: 0.1.1
httpx: >=1.0.0-dev,<2
pyinstaller: *
pyinstaller-hooks-contrib: *
safe-pysha3: *
