name: Release Flow

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
  build-agent-runner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,  macos-14, macos-14-large ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      # Set up Python with setup-python action and add it to PATH
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.10"

      - name: Add Python to PATH
        run: |
          echo "${{ steps.setup-python.outputs.python-path }}" >> $GITHUB_PATH

      - name: Install and configure Poetry
        run: pip install poetry

      - name: Build Agent Runner
        run: |
            make build-agent-runner

      - name: rename the file
        if: runner.os != 'Windows'
        run: | 
          export FILENAME=`echo -n agent_runner_${{runner.os}}_${{runner.arch}}|tr '[:upper:]' '[:lower:]'`
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV; 
          mv dist/agent_runner_bin dist/${FILENAME}

      - name: rename the file
        if: runner.os == 'Windows'
        run: | 
          export FILENAME=`echo -n agent_runner_${{runner.os}}_${{runner.arch}}.exe|tr '[:upper:]' '[:lower:]'`
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV; 
          mv dist/agent_runner_bin.exe dist/${FILENAME}

      - name: Upload Release Assets Windows
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.FILENAME}}
          path: dist/${{env.FILENAME}}

  upload-assets:
      needs: build-agent-runner
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: agent_runner_macos_x64
            path: ./dist/

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: agent_runner_macos_arm64
            path: ./dist/
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: agent_runner_windows_x64.exe
            path: ./dist/
        - name: List files
          run: ls ./dist/
        - name: Publish Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              ./dist/agent_runner*